name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t keysmustafa/skypro_mnysan_app:$GITHUB_REF_NAME-$GITHUB_RUN_UD .
      - name: docker login
        run: echo ${{ secrets.TOKEN_DOCKER }} | docker login -u ${{ secrets.USERNAME_DOCKER }} --password-stdin
      - name: docker push
        run: docker push keysmustafa/skypro_mnysan_app:$GITHUB_REF_NAME-$GITHUB_RUN_UD
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render config
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker_compose.yaml
          cat docker_ci_config.py | envsubst > deploy/docker_ci_config_render.py
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker_compose.yaml,deploy/docker_ci_config_render.py"
          target: "flask_app_ci"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd flask_app_ci
            echo ${{ secrets.PASSWORD }} | sudo -S docker_compose up -d
